---
title: Remote
author: ''
date: '2018-12-01'
slug: remote
categories: []
tags: [book]
description: 'Remote'
topics: []
---


Remote by Jason Fried and David Heinemeier Hansson at October 29, 2013: 

## content:
THE TIME IS RIGHT FOR REMOTE WORK

Why work doesn’t happen at work

Stop commuting your life away

It’s the technology, stupid

Escaping 9am–5pm

End of city monopoly

The new luxury

Talent isn’t bound by the hubs

It’s not about the money

But saving is always nice

Not all or nothing

Still a trade-off

You’re probably already doing it

DEALING WITH EXCUSES

Magic only happens when we’re all in a room

If I can’t see them, how do I know they’re working?

People’s homes are full of distractions

Only the office can be secure

Who will answer the phone?

Big business doesn’t do it, so why should we?

Others would get jealous

What about culture?

I need an answer now!

But I’ll lose control

We paid a lot of money for this office

That wouldn’t work for our size or industry

HOW TO COLLABORATE REMOTELY 

Thou shalt overlap

Seeing is believing

All out in the open

The virtual water cooler

Forward motion 

The work is what matters

Not just for people who are out of town

Disaster ready

Easy on the M&Ms

BEWARE THE DRAGONS 

Cabin fever

Check-in, check-out

Ergonomic basics

Mind the gut 

The lone outpost 
Working with clients

Taxes, accounting, laws, oh my!
HIRING AND KEEPING THE BEST 

It’s a big world

Life moves on

Keep the good times going

Seeking a human

No parlor tricks

The cost of thriving

Great remote workers are simply great workers

On writing well

Test project

Meeting them in person

Contractors know the drill

MANAGING REMOTE WORKERS 

When’s the right time to go remote?

Stop managing the chairs

Meetups and sprints

Lessons from open source

Level the playing field

One-on-ones

Remove the roadblocks

Be on the lookout for overwork, not underwork

Using scarcity to your advantage

LIFE AS A REMOTE WORKER 

Building a routine

Morning remote, afternoon local

Compute different

Working alone in a crowd

Staying motivated

Nomadic freedom

A change of scenery

Family time

No extra space at home

Making sure you’re not ignored


## video:

https://www.youtube.com/watch?v=y2AOhWGLAJY

https://www.youtube.com/watch?v=5XD2kNopsUs

https://www.youtube.com/watch?v=o6706ZzYocQ



