---
title: rstudio::conf 2019
author: ''
date: '2019-01-15'
slug: rstudio-conf-2019
categories: []
tags: []
description: 'rstudio::conf 2019'
topics: []
---

I segment the talk into following groups:Get,clean,visualize,model,present,other 

[Rstudio conference 2019](https://resources.rstudio.com/rstudio-conf-2019) hosted during January 15 - 18 in Austin, TX

[Rstudio conference 2020](https://www.rstudio.com/conference/) will be hosted in San Francisco, California from January 27–30, 2020

--------------------------------------------------------


## Get:


### [Databases using R: The latest - Edgar Ruiz](https://resources.rstudio.com/rstudio-conf-2019/databases-using-r-the-latest)

connect with database with R in connection pane


--------------------------------------------------------

## Clean:

### [Lazy evaluation - Jenny Bryan](https://resources.rstudio.com/rstudio-conf-2019/lazy-evaluation)

The "tidy eval" framework is implemented in the rlang package and is rolling out in packages across the tidyverse and beyond.explain metaprogramming and non standard evaluation 


### [Melt the clock Tidy time series analysis - Earo Wang
]
(https://resources.rstudio.com/rstudio-conf-2019/melt-the-clock-tidy-time-series-analysis)



## Visualize:


### [3D mapping, plotting, and printing with rayshader - Tyler Morgan-Wall](https://resources.rstudio.com/rstudio-conf-2019/3d-mapping-plotting-and-printing-with-rayshader)

3D map Visualization



### [gganimate live cookbook - Thomas Lin Pedersen](https://resources.rstudio.com/rstudio-conf-2019/gganimate-live-cookbook)

make ggplot move


--------------------------------------------------------

## Model:


### [Introducing mlflow - Kevin Kuo](https://resources.rstudio.com/rstudio-conf-2019/introducing-mlflow)


use mlflow to record modeling building result 


### [parsnip: A tidy model interface - Max Kuhn](https://resources.rstudio.com/rstudio-conf-2019/parsnip-a-tidy-model-interface)


parsnip is a new tidymodels package that generalizes model interfaces across packages. The idea is to have a single function interface for types of specific models 


### [Solving the model representation problem with broom - Alex Hayes](https://resources.rstudio.com/rstudio-conf-2019/solving-the-model-representation-problem-with-broom)


### [Using R, the Tidyverse, H2O, and Shiny to reduce employee attrition - Matt Dancho](https://resources.rstudio.com/rstudio-conf-2019/using-r-the-tidyverse-h2o-and-shiny-to-reduce-employee-attrition)





--------------------------------------------------------



## Present:

### [RStudio Connect Past, present, and future - Jeff Allen](https://resources.rstudio.com/rstudio-conf-2019/rstudio-connect-past-present-and-future)

product RStudio Connect  can share the R code and output to organization with  authentication and email notification.


### [Shiny in production: Principles, practices, and tools - Joe Cheng](https://resources.rstudio.com/rstudio-conf-2019/shiny-in-production-principles-practices-and-tools-joe-cheng)

can shiny be used for production?

- 2015 answer:Yes,its quite possible

- 2019 answer:Yes,its quite esay

challenges for shiny in production:cultural/Organizational/Technical

New tools for shiny:shinytest/shinyloadtest/profvis/plot caching/Async

1.use shinyloadtest to see if its fast
2.if not,use profvis to see whats making it slow
3.Optimize
- move work out of Shiny
- make code faster
- use caching
- use async



### [Reactlog 2.0: Debugging the state of Shiny - Barret Schloerke](https://resources.rstudio.com/rstudio-conf-2019/reactlog-2-0-debugging-the-state-of-shiny)


### [pagedown: Creating beautiful PDFs with R Markdown and CSS - Yihui Xie](https://resources.rstudio.com/rstudio-conf-2019/pagedown-creating-beautiful-pdfs-with-r-markdown-and-css)
pakcage pagedown create PDF,business card,poster.




### [Introducing the gt package - Rich Iannone](https://resources.rstudio.com/rstudio-conf-2019/introducing-the-gt-package)
make formatted table in html and embedded in email body




### [Democratizing R with Plumber APIs - James Blair](https://resources.rstudio.com/rstudio-conf-2019/democratizing-r-with-plumber-apis)
Create API server for user interaction programmatically. For example,user post a request with input parameter and will get back a predict respond.


### [The unreasonable effectiveness of public work - David Robinson](https://resources.rstudio.com/rstudio-conf-2019/the-unreasonable-effectiveness-of-public-work)


### [R Markdown: The bigger picture - Garrett Grolemund
](https://resources.rstudio.com/rstudio-conf-2019/r-markdown-the-bigger-picture)


## Other:

### [Welcome to rstudio::conf 2019](https://resources.rstudio.com/rstudio-conf-2019/welcome-to-rstudio-conf-2019)






### [The next million R users - Carl Howe](https://resources.rstudio.com/rstudio-conf-2019/the-next-million-r-users
)
Teach next million R users.

Why R :1.community , 2.package ,3.visualization,4.free


### [Configuration management tools for the R admin - Kelly O'Briant](https://resources.rstudio.com/rstudio-conf-2019/configuration-management-tools-for-the-r-admin)
R admin set up





### [New language features in RStudio - Jonathan McPherson](https://resources.rstudio.com/rstudio-conf-2019/new-language-features-in-rstudio)
how to use SQL , python and R in Rstudio and Backgroup job





### [Empowering a data team with RStudio addins - Hao Zhu](https://resources.rstudio.com/rstudio-conf-2019/empowering-a-data-team-with-rstudio-addins)

create rstudio add-in

### [It depends: A dialog about dependencies - Jim Hester](https://resources.rstudio.com/rstudio-conf-2019/it-depends-a-dialog-about-dependencies)

check package or projects depends,number of function used,size ect with package itdepends




### [Welcome and RStudio Vision - Tareef Kawaf](https://resources.rstudio.com/rstudio-conf-2019/opening-keynote-tareef-kawaf)

- Why code:Repeatable;Inspectable;Resuable;Diffable.
- code is communication

























