---
title: Coronavirus Visualization in R and Python
author: ''
date: '2020-02-03'
slug: coronavirus-visualization-in-r-and-python
categories: []
tags: []
description: 'Coronavirus Visualization in R and Python'
topics: []
---


```{r}
library(reticulate)
py_run_string("import os as os")
py_run_string("os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Users/User/Anaconda3/Library/plugins/platforms'")
```

# 1. Coronavirus Visualization in R


```{R message=FALSE ,warning=FALSE}
library(jsonlite)
library(ggplot2)
library(gganimate)
library(tidyverse)
library(plotly)
```

```{R message=FALSE ,warning=FALSE}
url = 'https://view.inews.qq.com/g2/getOnsInfo?name=disease_h5&callback=1580373566110'
data001 = readLines(url, encoding="UTF-8")
data001 = sub("^\\d+", "", data001)
data001 = sub("^\\(", "", data001)
data001 = sub("\\)$", "", data001)

data002 = fromJSON(data001)
data003= fromJSON(data002$data)
```




## linechart with plotly package



```{R message=FALSE ,warning=FALSE}
trend001=data003$chinaDayList

trend001$date_time=as.Date(trend001$date, "%m.%d")
trend001$confirm=as.numeric(trend001$confirm)
trend001$suspect=as.numeric(trend001$suspect)
trend001$dead=as.numeric(trend001$dead)
trend001$heal=as.numeric(trend001$heal)
trend002=trend001 %>% mutate(
         confirm_growth = confirm - lag(confirm),
         confirm_change_Rate= confirm_growth /confirm ,
         suspect_growth = suspect - lag(suspect),
         suspect_change_Rate= suspect_growth /suspect ,
         dead_growth = dead - lag(dead),
         dead_change_Rate= dead_growth /dead ,
         heal_growth = heal - lag(heal),
         heal_change_Rate= heal_growth /heal 
         ) %>% filter(date_time>='2020-01-15')

glimpse(trend002)
```


```{R message=FALSE ,warning=FALSE}
p <- plot_ly(trend001, x = ~date_time, y = ~confirm, name = 'confirm',type = 'scatter', mode = 'lines+markers')%>%add_trace(x = ~date_time, y = ~suspect, name = 'suspect', mode = 'lines+markers') %>% layout(
    title = "Coronavirus Visualization",
      xaxis = list(title = "date"),
      yaxis = list(title = "person")
    )
p
  
```

```{R message=FALSE ,warning=FALSE}
p <- plot_ly(trend002, x = ~date_time, y = ~confirm_change_Rate , name = 'confirm_change_Rate ',type = 'scatter', mode = 'lines+markers')%>%
  add_trace(x = ~date_time, y = ~suspect_change_Rate, name = 'suspect_change_Rate', mode = 'lines+markers')%>%
  add_trace(x = ~date_time, y = ~dead_change_Rate, name = 'dead_change_Rate', mode = 'lines+markers')%>% 
    add_trace(x = ~date_time, y = ~heal_change_Rate, name = 'heal_change_Rate', mode = 'lines+markers')%>% 
  layout(
    title = "Coronavirus Visualization",
      xaxis = list(title = "date"),
      yaxis = list(title = "increase rate compare with last day")
    )
p
  
```


## barchart with plotly package

```{R message=FALSE ,warning=FALSE}
#remotes::install_github("GuangchuangYu/nCov2019")
library(nCov2019)
```



```{R message=FALSE ,warning=FALSE}
x=get_nCov2019()
```


```{R message=FALSE ,warning=FALSE}
daily001=get_nCov2019()

time(daily001)

daily002=daily001[]
```



```{R message=FALSE ,warning=FALSE}
p <- plot_ly(daily002, x = ~name, y = ~confirm, type = 'bar',text = ~confirm, textposition = 'auto') %>%  
layout(
     
     xaxis = list(title = time(daily001),
     categoryorder = "confirm_num",
     categoryarray = ~name)
)
p
```


# 2. Coronavirus Visualization in Python


## linechart with plotly package

```{python}
py_trend002=r.trend002
py_daily002=r.daily002
```

```{python}

import matplotlib as mpl
mpl.rcParams['font.sans-serif'] = ['SimHei']
mpl.rcParams['font.serif'] = ['SimHei']
import seaborn as sns
sns.set_style("darkgrid",{"font.sans-serif":['simhei', 'Arial']})
py_daily002.head()
```


```{r}
#py_install("seaborn")
```


```{python}
import seaborn as sns
import matplotlib.pyplot as plt

sns.lineplot(x="date_time", y="suspect",data=py_trend002)
sns.lineplot(x="date_time", y="dead",data=py_trend002).set_title("Coronavirus")
plt.legend(title='', loc='upper left', labels=['suspecth', 'dead'])
plt.tight_layout()
plt.show()
```

```{python message=FALSE ,warning=FALSE}

import seaborn as sns
import matplotlib.pyplot as plt

chart=sns.barplot(x='name', y='confirm', palette="rocket",data=py_daily002)

chart.set_xticklabels(chart.get_xticklabels(), rotation=90)

plt.show()
```











